In [42]:
# Data handling
import pandas as pd
import numpy as np

# Progress bars
from tqdm import tqdm

# Hugging Face Transformers (model, tokenizer, pipelines)
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    pipeline,
    DataCollatorForSeq2Seq,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    TrainingArguments,
    EarlyStoppingCallback,
    PegasusTokenizer,
)

# Metrics and Evaluation
from rouge_score import rouge_scorer
from sklearn.metrics import average_precision_score

# Torch for GPU
import torch

# For displaying results in notebook
from IPython.display import display

# Plotting and Visualization (optional but useful)
import matplotlib.pyplot as plt
import seaborn as sns

# Logging
import logging

import torch
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

Using device: cuda

In [44]:
train_df = pd.read_csv('train.csv')
val_df = pd.read_csv('validation.csv')
test_df = pd.read_csv('test.csv')

print("Train set:")
display(train_df.head(2))
print("Validation set:")
display(val_df.head(2))
print("Test set:")
display(test_df.head(2))

Train set:

,id,article,highlights
0,0001d1afc246a7964130f43ae940af6bc6c57f01,By . Associated Press . PUBLISHED: . 14:11 EST...,"Bishop John Folda, of North Dakota, is taking ..."
1,0002095e55fcbd3a2f366d9bf92a95433dc305ef,(CNN) -- Ralph Mata was an internal affairs li...,Criminal complaint: Cop used his role to help ...

Validation set:

,id,article,highlights
0,61df4979ac5fcc2b71be46ed6fe5a46ce7f071c3,"Sally Forrest, an actress-dancer who graced th...","Sally Forrest, an actress-dancer who graced th..."
1,21c0bd69b7e7df285c3d1b1cf56d4da925980a68,A middle-school teacher in China has inked hun...,Works include pictures of Presidential Palace ...

Test set:

,id,article,highlights
0,92c514c913c0bdfe25341af9fd72b29db544099b,Ever noticed how plane seats appear to be gett...,Experts question if packed out planes are put...
1,2003841c7dc0e7c5b1a248f9cd536d727f27a45a,A drunk teenage boy had to be rescued by secur...,Drunk teenage boy climbed into lion enclosure ...

In [4]:
print("Train columns:", train_df.columns.tolist())
print("Validation columns:", val_df.columns.tolist())
print("Test columns:", test_df.columns.tolist())

# Check for missing values
print("Missing values in train:")
print(train_df.isnull().sum())
print("Missing values in validation:")
print(val_df.isnull().sum())
print("Missing values in test:")
print(test_df.isnull().sum())

Train columns: ['id', 'article', 'highlights']
Validation columns: ['id', 'article', 'highlights']
Test columns: ['id', 'article', 'highlights']
Missing values in train:
id            0
article       0
highlights    0
dtype: int64
Missing values in validation:
id            0
article       0
highlights    0
dtype: int64
Missing values in test:
id            0
article       0
highlights    0
dtype: int64

In [5]:
# Remove missing values if any
train_df = train_df.dropna(subset=['article', 'highlights'])
val_df = val_df.dropna(subset=['article', 'highlights'])
test_df = test_df.dropna(subset=['article', 'highlights'])

# Strip whitespace
train_df['article'] = train_df['article'].str.strip()
train_df['highlights'] = train_df['highlights'].str.strip()
val_df['article'] = val_df['article'].str.strip()
val_df['highlights'] = val_df['highlights'].str.strip()
test_df['article'] = test_df['article'].str.strip()
test_df['highlights'] = test_df['highlights'].str.strip()

In [6]:
print("Average article length (train):", train_df['article'].str.len().mean())
print("Average summary length (train):", train_df['highlights'].str.len().mean())

Average article length (train): 4033.6608652342456
Average summary length (train): 294.7703900554834

In [7]:
# Models to benchmark (feel free to swap with other variants if needed)
model_infos = [
    {"name": "BART", "hf_id": "facebook/bart-large-cnn"},
    {"name": "T5", "hf_id": "t5-base"},
    {"name": "Pegasus", "hf_id": "google/pegasus-cnn_dailymail"},
    {"name": "FLAN-T5", "hf_id": "google/flan-t5-base"},
    {"name": "BigBird-Pegasus", "hf_id": "google/bigbird-pegasus-large-arxiv"},  # Or use the cnn_dailymail variant
]

# Function to load model and tokenizer
def load_model(model_hf_id):
    if "pegasus" in model_hf_id:
        # Force slow tokenizer for Pegasus
        tokenizer = PegasusTokenizer.from_pretrained(model_hf_id, use_fast=False)
    else:
        tokenizer = AutoTokenizer.from_pretrained(model_hf_id)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_hf_id).to(device)
    model.eval()
    return model, tokenizer

In [8]:
def generate_summary(model, tokenizer, article, 
                     max_input_length=1024, max_output_length=128):
    # Tokenize and truncate long articles as needed
    inputs = tokenizer(
        article, 
        return_tensors="pt",
        truncation=True, 
        max_length=max_input_length,
        padding="max_length"
    ).to(device)
    with torch.no_grad():
        summary_ids = model.generate(
            **inputs, 
            max_length=max_output_length,
            min_length=30,
            length_penalty=2.0,
            num_beams=4,
            early_stopping=True,
            no_repeat_ngram_size=3
        )
    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

In [16]:
# Use a subset for demo/experimentation (increase to more samples for final runs)
N_SAMPLES = 100
sample_df = test_df.sample(N_SAMPLES, random_state=42).reset_index(drop=True)

all_results = []

for m_info in model_infos:
    print(f"Evaluating: {m_info['name']}")
    model, tokenizer = load_model(m_info['hf_id'])
    gens = []
    for article in tqdm(sample_df['article'], desc=f"Summarizing ({m_info['name']})"):
        summary = generate_summary(model, tokenizer, article)
        gens.append(summary)
    # Compute ROUGE
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
    scores = [
        scorer.score(ref, pred)
        for ref, pred in zip(sample_df['highlights'], gens)
    ]
    # Aggregate ROUGE scores
    rouge1 = np.mean([s['rouge1'].fmeasure for s in scores])
    rouge2 = np.mean([s['rouge2'].fmeasure for s in scores])
    rougel = np.mean([s['rougeL'].fmeasure for s in scores])
    all_results.append({
        "Model": m_info['name'],
        "ROUGE-1": rouge1,
        "ROUGE-2": rouge2,
        "ROUGE-L": rougel,
    })
    # Save outputs for later qualitative inspection
    sample_df[f'{m_info["name"]}_gen'] = gens

# Final results as DataFrame
results_df = pd.DataFrame(all_results)
display(results_df)

Evaluating: BART

Summarizing (BART): 100%|██████████| 100/100 [02:32<00:00,  1.53s/it]

Evaluating: T5

Summarizing (T5): 100%|██████████| 100/100 [03:52<00:00,  2.32s/it]

Evaluating: Pegasus

pytorch_model.bin:   0%|          | 0.00/2.28G [00:00<?, ?B/s]

C:\Users\Adidya\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Adidya\M_H_Project\cache\models--google--pegasus-cnn_dailymail. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

model.safetensors:   0%|          | 0.00/2.28G [00:00<?, ?B/s]

Some weights of PegasusForConditionalGeneration were not initialized from the model checkpoint at google/pegasus-cnn_dailymail and are newly initialized: ['model.decoder.embed_positions.weight', 'model.encoder.embed_positions.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

generation_config.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

Summarizing (Pegasus):   0%|          | 0/100 [00:00<?, ?it/s]Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.58.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.

Summarizing (Pegasus):   1%|          | 1/100 [00:01<02:41,  1.63s/it]
Summarizing (Pegasus):   2%|▏         | 2/100 [00:03<03:06,  1.90s/it]
Summarizing (Pegasus):   3%|▎         | 3/100 [00:04<02:32,  1.57s/it]
Summarizing (Pegasus):   4%|▍         | 4/100 [00:06<02:21,  1.48s/it]
Summarizing (Pegasus):   5%|▌         | 5/100 [00:08<02:34,  1.63s/it]
Summarizing (Pegasus):   6%|▌         | 6/100 [00:09<02:22,  1.52s/it]
Summarizing (Pegasus):   7%|▋         | 7/100 [00:12<03:09,  2.04s/it]
Summarizing (Pegasus):   8%|▊         | 8/100 [00:14<02:59,  1.96s/it]
Summarizing (Pegasus):   9%|▉         | 9/100 [00:16<03:09,  2.08s/it]
Summarizing (Pegasus):  10%|█         | 10/100 [00:18<03:02,  2.02s/it]
Summarizing (Pegasus):  11%|█         | 11/100 [00:19<02:42,  1.83s/it]
Summarizing (Pegasus):  12%|█▏        | 12/100 [00:22<03:02,  2.07s/it]
Summarizing (Pegasus):  13%|█▎        | 13/100 [00:24<02:48,  1.94s/it]
Summarizing (Pegasus):  14%|█▍        | 14/100 [00:25<02:39,  1.86s/it]
Summarizing (Pegasus):  15%|█▌        | 15/100 [00:27<02:24,  1.70s/it]
Summarizing (Pegasus):  16%|█▌        | 16/100 [00:29<02:38,  1.88s/it]
Summarizing (Pegasus):  17%|█▋        | 17/100 [00:31<02:26,  1.77s/it]
Summarizing (Pegasus):  18%|█▊        | 18/100 [00:32<02:29,  1.82s/it]
Summarizing (Pegasus):  19%|█▉        | 19/100 [00:34<02:21,  1.75s/it]
Summarizing (Pegasus):  20%|██        | 20/100 [00:36<02:19,  1.74s/it]
Summarizing (Pegasus):  21%|██        | 21/100 [00:38<02:18,  1.75s/it]
Summarizing (Pegasus):  22%|██▏       | 22/100 [00:39<02:08,  1.65s/it]
Summarizing (Pegasus):  23%|██▎       | 23/100 [00:41<02:09,  1.69s/it]
Summarizing (Pegasus):  24%|██▍       | 24/100 [00:42<02:05,  1.65s/it]
Summarizing (Pegasus):  25%|██▌       | 25/100 [00:45<02:24,  1.92s/it]
Summarizing (Pegasus):  26%|██▌       | 26/100 [00:47<02:21,  1.91s/it]
Summarizing (Pegasus):  27%|██▋       | 27/100 [00:48<02:04,  1.70s/it]
Summarizing (Pegasus):  28%|██▊       | 28/100 [00:49<01:54,  1.59s/it]
Summarizing (Pegasus):  29%|██▉       | 29/100 [00:51<01:47,  1.52s/it]
Summarizing (Pegasus):  30%|███       | 30/100 [00:52<01:52,  1.61s/it]
Summarizing (Pegasus):  31%|███       | 31/100 [00:54<01:49,  1.58s/it]
Summarizing (Pegasus):  32%|███▏      | 32/100 [00:56<01:58,  1.74s/it]
Summarizing (Pegasus):  33%|███▎      | 33/100 [00:59<02:18,  2.07s/it]
Summarizing (Pegasus):  34%|███▍      | 34/100 [01:01<02:11,  1.99s/it]
Summarizing (Pegasus):  35%|███▌      | 35/100 [01:03<02:08,  1.98s/it]
Summarizing (Pegasus):  36%|███▌      | 36/100 [01:04<02:01,  1.89s/it]
Summarizing (Pegasus):  37%|███▋      | 37/100 [01:05<01:43,  1.65s/it]
Summarizing (Pegasus):  38%|███▊      | 38/100 [01:07<01:31,  1.48s/it]
Summarizing (Pegasus):  39%|███▉      | 39/100 [01:08<01:33,  1.54s/it]
Summarizing (Pegasus):  40%|████      | 40/100 [01:10<01:31,  1.53s/it]
Summarizing (Pegasus):  41%|████      | 41/100 [01:11<01:26,  1.47s/it]
Summarizing (Pegasus):  42%|████▏     | 42/100 [01:13<01:29,  1.54s/it]
Summarizing (Pegasus):  43%|████▎     | 43/100 [01:14<01:22,  1.44s/it]
Summarizing (Pegasus):  44%|████▍     | 44/100 [01:15<01:17,  1.38s/it]
Summarizing (Pegasus):  45%|████▌     | 45/100 [01:17<01:24,  1.54s/it]
Summarizing (Pegasus):  46%|████▌     | 46/100 [01:18<01:19,  1.48s/it]
Summarizing (Pegasus):  47%|████▋     | 47/100 [01:20<01:15,  1.42s/it]
Summarizing (Pegasus):  48%|████▊     | 48/100 [01:21<01:15,  1.45s/it]
Summarizing (Pegasus):  49%|████▉     | 49/100 [01:23<01:25,  1.67s/it]
Summarizing (Pegasus):  50%|█████     | 50/100 [01:25<01:24,  1.70s/it]
Summarizing (Pegasus):  51%|█████     | 51/100 [01:27<01:22,  1.68s/it]
Summarizing (Pegasus):  52%|█████▏    | 52/100 [01:28<01:16,  1.60s/it]
Summarizing (Pegasus):  53%|█████▎    | 53/100 [01:31<01:26,  1.84s/it]
Summarizing (Pegasus):  54%|█████▍    | 54/100 [01:33<01:32,  2.00s/it]
Summarizing (Pegasus):  55%|█████▌    | 55/100 [01:34<01:21,  1.82s/it]
Summarizing (Pegasus):  56%|█████▌    | 56/100 [01:36<01:15,  1.72s/it]
Summarizing (Pegasus):  57%|█████▋    | 57/100 [01:38<01:13,  1.72s/it]
Summarizing (Pegasus):  58%|█████▊    | 58/100 [01:39<01:10,  1.68s/it]
Summarizing (Pegasus):  59%|█████▉    | 59/100 [01:40<01:00,  1.48s/it]
Summarizing (Pegasus):  60%|██████    | 60/100 [01:42<01:00,  1.51s/it]
Summarizing (Pegasus):  61%|██████    | 61/100 [01:43<00:54,  1.39s/it]
Summarizing (Pegasus):  62%|██████▏   | 62/100 [01:45<00:56,  1.47s/it]
Summarizing (Pegasus):  63%|██████▎   | 63/100 [01:47<00:59,  1.61s/it]
Summarizing (Pegasus):  64%|██████▍   | 64/100 [01:48<00:59,  1.64s/it]
Summarizing (Pegasus):  65%|██████▌   | 65/100 [01:50<00:57,  1.65s/it]
Summarizing (Pegasus):  66%|██████▌   | 66/100 [01:51<00:49,  1.45s/it]
Summarizing (Pegasus):  67%|██████▋   | 67/100 [01:53<00:51,  1.56s/it]
Summarizing (Pegasus):  68%|██████▊   | 68/100 [01:54<00:44,  1.41s/it]
Summarizing (Pegasus):  69%|██████▉   | 69/100 [01:56<00:49,  1.59s/it]
Summarizing (Pegasus):  70%|███████   | 70/100 [01:58<00:56,  1.90s/it]
Summarizing (Pegasus):  71%|███████   | 71/100 [02:00<00:56,  1.95s/it]
Summarizing (Pegasus):  72%|███████▏  | 72/100 [02:03<01:01,  2.20s/it]
Summarizing (Pegasus):  73%|███████▎  | 73/100 [02:04<00:50,  1.87s/it]
Summarizing (Pegasus):  74%|███████▍  | 74/100 [02:06<00:46,  1.81s/it]
Summarizing (Pegasus):  75%|███████▌  | 75/100 [02:08<00:46,  1.87s/it]
Summarizing (Pegasus):  76%|███████▌  | 76/100 [02:10<00:44,  1.86s/it]
Summarizing (Pegasus):  77%|███████▋  | 77/100 [02:11<00:37,  1.63s/it]
Summarizing (Pegasus):  78%|███████▊  | 78/100 [02:14<00:43,  1.96s/it]
Summarizing (Pegasus):  79%|███████▉  | 79/100 [02:15<00:38,  1.82s/it]
Summarizing (Pegasus):  80%|████████  | 80/100 [02:16<00:32,  1.62s/it]
Summarizing (Pegasus):  81%|████████  | 81/100 [02:18<00:33,  1.75s/it]
Summarizing (Pegasus):  82%|████████▏ | 82/100 [02:20<00:28,  1.60s/it]
Summarizing (Pegasus):  83%|████████▎ | 83/100 [02:21<00:27,  1.63s/it]
Summarizing (Pegasus):  84%|████████▍ | 84/100 [02:23<00:27,  1.73s/it]
Summarizing (Pegasus):  85%|████████▌ | 85/100 [02:24<00:23,  1.54s/it]
Summarizing (Pegasus):  86%|████████▌ | 86/100 [02:26<00:20,  1.43s/it]
Summarizing (Pegasus):  87%|████████▋ | 87/100 [02:27<00:17,  1.38s/it]
Summarizing (Pegasus):  88%|████████▊ | 88/100 [02:28<00:17,  1.42s/it]
Summarizing (Pegasus):  89%|████████▉ | 89/100 [02:29<00:14,  1.32s/it]
Summarizing (Pegasus):  90%|█████████ | 90/100 [02:31<00:13,  1.39s/it]
Summarizing (Pegasus):  91%|█████████ | 91/100 [02:33<00:13,  1.48s/it]
Summarizing (Pegasus):  92%|█████████▏| 92/100 [02:34<00:12,  1.58s/it]
Summarizing (Pegasus):  93%|█████████▎| 93/100 [02:36<00:10,  1.43s/it]
Summarizing (Pegasus):  94%|█████████▍| 94/100 [02:38<00:10,  1.67s/it]
Summarizing (Pegasus):  95%|█████████▌| 95/100 [02:39<00:07,  1.55s/it]
Summarizing (Pegasus):  96%|█████████▌| 96/100 [02:40<00:05,  1.46s/it]
Summarizing (Pegasus):  97%|█████████▋| 97/100 [02:42<00:04,  1.44s/it]
Summarizing (Pegasus):  98%|█████████▊| 98/100 [02:43<00:02,  1.30s/it]
Summarizing (Pegasus):  99%|█████████▉| 99/100 [02:44<00:01,  1.31s/it]
Summarizing (Pegasus): 100%|██████████| 100/100 [02:45<00:00,  1.66s/it]

Evaluating: FLAN-T5

tokenizer_config.json:   0%|          | 0.00/2.54k [00:00<?, ?B/s]

C:\Users\Adidya\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Adidya\M_H_Project\cache\models--google--flan-t5-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.42M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/2.20k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.40k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/990M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

Summarizing (FLAN-T5): 100%|██████████| 100/100 [04:25<00:00,  2.65s/it]

Evaluating: BigBird-Pegasus

tokenizer_config.json:   0%|          | 0.00/1.19k [00:00<?, ?B/s]

C:\Users\Adidya\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Adidya\M_H_Project\cache\models--google--bigbird-pegasus-large-arxiv. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

spiece.model:   0%|          | 0.00/1.92M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/775 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.51M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/1.05k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.31G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.31G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/232 [00:00<?, ?B/s]

Summarizing (BigBird-Pegasus):   0%|          | 0/100 [00:00<?, ?it/s]
Summarizing (BigBird-Pegasus):   1%|          | 1/100 [00:04<07:35,  4.61s/it]
Summarizing (BigBird-Pegasus):   2%|▏         | 2/100 [00:06<04:37,  2.84s/it]
Summarizing (BigBird-Pegasus):   3%|▎         | 3/100 [00:08<04:05,  2.53s/it]
Summarizing (BigBird-Pegasus):   4%|▍         | 4/100 [00:13<05:27,  3.41s/it]
Summarizing (BigBird-Pegasus):   5%|▌         | 5/100 [00:15<04:32,  2.86s/it]
Summarizing (BigBird-Pegasus):   6%|▌         | 6/100 [00:16<03:59,  2.55s/it]
Summarizing (BigBird-Pegasus):   7%|▋         | 7/100 [00:22<05:14,  3.38s/it]
Summarizing (BigBird-Pegasus):   8%|▊         | 8/100 [00:27<05:58,  3.90s/it]
Summarizing (BigBird-Pegasus):   9%|▉         | 9/100 [00:30<05:45,  3.80s/it]
Summarizing (BigBird-Pegasus):  10%|█         | 10/100 [00:33<05:04,  3.39s/it]
Summarizing (BigBird-Pegasus):  11%|█         | 11/100 [00:38<05:50,  3.93s/it]
Summarizing (BigBird-Pegasus):  12%|█▏        | 12/100 [00:43<06:11,  4.22s/it]
Summarizing (BigBird-Pegasus):  13%|█▎        | 13/100 [00:45<05:23,  3.72s/it]
Summarizing (BigBird-Pegasus):  14%|█▍        | 14/100 [00:50<05:51,  4.08s/it]
Summarizing (BigBird-Pegasus):  15%|█▌        | 15/100 [00:52<04:59,  3.52s/it]
Summarizing (BigBird-Pegasus):  16%|█▌        | 16/100 [00:57<05:19,  3.80s/it]
Summarizing (BigBird-Pegasus):  17%|█▋        | 17/100 [01:02<05:44,  4.16s/it]
Summarizing (BigBird-Pegasus):  18%|█▊        | 18/100 [01:07<06:02,  4.43s/it]
Summarizing (BigBird-Pegasus):  19%|█▉        | 19/100 [01:12<06:11,  4.59s/it]
Summarizing (BigBird-Pegasus):  20%|██        | 20/100 [01:17<06:15,  4.69s/it]
Summarizing (BigBird-Pegasus):  21%|██        | 21/100 [01:22<06:14,  4.74s/it]
Summarizing (BigBird-Pegasus):  22%|██▏       | 22/100 [01:24<05:04,  3.91s/it]
Summarizing (BigBird-Pegasus):  23%|██▎       | 23/100 [01:26<04:20,  3.39s/it]
Summarizing (BigBird-Pegasus):  24%|██▍       | 24/100 [01:30<04:37,  3.65s/it]
Summarizing (BigBird-Pegasus):  25%|██▌       | 25/100 [01:34<04:45,  3.81s/it]
Summarizing (BigBird-Pegasus):  26%|██▌       | 26/100 [01:38<04:53,  3.96s/it]
Summarizing (BigBird-Pegasus):  27%|██▋       | 27/100 [01:40<04:03,  3.34s/it]
Summarizing (BigBird-Pegasus):  28%|██▊       | 28/100 [01:42<03:27,  2.89s/it]
Summarizing (BigBird-Pegasus):  29%|██▉       | 29/100 [01:47<03:54,  3.31s/it]
Summarizing (BigBird-Pegasus):  30%|███       | 30/100 [01:51<04:10,  3.58s/it]
Summarizing (BigBird-Pegasus):  31%|███       | 31/100 [01:55<04:21,  3.79s/it]
Summarizing (BigBird-Pegasus):  32%|███▏      | 32/100 [01:58<04:05,  3.61s/it]
Summarizing (BigBird-Pegasus):  33%|███▎      | 33/100 [02:02<04:14,  3.80s/it]
Summarizing (BigBird-Pegasus):  34%|███▍      | 34/100 [02:07<04:20,  3.94s/it]
Summarizing (BigBird-Pegasus):  35%|███▌      | 35/100 [02:11<04:22,  4.04s/it]
Summarizing (BigBird-Pegasus):  36%|███▌      | 36/100 [02:15<04:21,  4.09s/it]
Summarizing (BigBird-Pegasus):  37%|███▋      | 37/100 [02:19<04:15,  4.06s/it]
Summarizing (BigBird-Pegasus):  38%|███▊      | 38/100 [02:23<04:15,  4.12s/it]
Summarizing (BigBird-Pegasus):  39%|███▉      | 39/100 [02:25<03:31,  3.47s/it]
Summarizing (BigBird-Pegasus):  40%|████      | 40/100 [02:30<03:42,  3.70s/it]
Summarizing (BigBird-Pegasus):  41%|████      | 41/100 [02:32<03:13,  3.29s/it]
Summarizing (BigBird-Pegasus):  42%|████▏     | 42/100 [02:34<02:51,  2.96s/it]
Summarizing (BigBird-Pegasus):  43%|████▎     | 43/100 [02:36<02:26,  2.58s/it]
Summarizing (BigBird-Pegasus):  44%|████▍     | 44/100 [02:40<02:55,  3.13s/it]
Summarizing (BigBird-Pegasus):  45%|████▌     | 45/100 [02:45<03:13,  3.53s/it]
Summarizing (BigBird-Pegasus):  46%|████▌     | 46/100 [02:49<03:19,  3.69s/it]
Summarizing (BigBird-Pegasus):  47%|████▋     | 47/100 [02:53<03:28,  3.93s/it]
Summarizing (BigBird-Pegasus):  48%|████▊     | 48/100 [02:58<03:32,  4.08s/it]
Summarizing (BigBird-Pegasus):  49%|████▉     | 49/100 [03:02<03:32,  4.17s/it]
Summarizing (BigBird-Pegasus):  50%|█████     | 50/100 [03:06<03:32,  4.24s/it]
Summarizing (BigBird-Pegasus):  51%|█████     | 51/100 [03:08<02:49,  3.47s/it]
Summarizing (BigBird-Pegasus):  52%|█████▏    | 52/100 [03:12<02:58,  3.71s/it]
Summarizing (BigBird-Pegasus):  53%|█████▎    | 53/100 [03:15<02:31,  3.23s/it]
Summarizing (BigBird-Pegasus):  54%|█████▍    | 54/100 [03:19<02:41,  3.52s/it]
Summarizing (BigBird-Pegasus):  55%|█████▌    | 55/100 [03:23<02:48,  3.75s/it]
Summarizing (BigBird-Pegasus):  56%|█████▌    | 56/100 [03:25<02:26,  3.32s/it]
Summarizing (BigBird-Pegasus):  57%|█████▋    | 57/100 [03:30<02:34,  3.59s/it]
Summarizing (BigBird-Pegasus):  58%|█████▊    | 58/100 [03:34<02:40,  3.83s/it]
Summarizing (BigBird-Pegasus):  59%|█████▉    | 59/100 [03:38<02:42,  3.96s/it]
Summarizing (BigBird-Pegasus):  60%|██████    | 60/100 [03:41<02:19,  3.48s/it]
Summarizing (BigBird-Pegasus):  61%|██████    | 61/100 [03:45<02:24,  3.71s/it]
Summarizing (BigBird-Pegasus):  62%|██████▏   | 62/100 [03:49<02:28,  3.90s/it]
Summarizing (BigBird-Pegasus):  63%|██████▎   | 63/100 [03:53<02:20,  3.79s/it]
Summarizing (BigBird-Pegasus):  64%|██████▍   | 64/100 [03:56<02:15,  3.77s/it]
Summarizing (BigBird-Pegasus):  65%|██████▌   | 65/100 [04:01<02:17,  3.93s/it]
Summarizing (BigBird-Pegasus):  66%|██████▌   | 66/100 [04:05<02:16,  4.03s/it]
Summarizing (BigBird-Pegasus):  67%|██████▋   | 67/100 [04:09<02:10,  3.96s/it]
Summarizing (BigBird-Pegasus):  68%|██████▊   | 68/100 [04:13<02:11,  4.10s/it]
Summarizing (BigBird-Pegasus):  69%|██████▉   | 69/100 [04:17<02:08,  4.16s/it]
Summarizing (BigBird-Pegasus):  70%|███████   | 70/100 [04:20<01:45,  3.53s/it]
Summarizing (BigBird-Pegasus):  71%|███████   | 71/100 [04:24<01:48,  3.75s/it]
Summarizing (BigBird-Pegasus):  72%|███████▏  | 72/100 [04:28<01:50,  3.96s/it]
Summarizing (BigBird-Pegasus):  73%|███████▎  | 73/100 [04:30<01:31,  3.37s/it]
Summarizing (BigBird-Pegasus):  74%|███████▍  | 74/100 [04:34<01:27,  3.37s/it]
Summarizing (BigBird-Pegasus):  75%|███████▌  | 75/100 [04:38<01:30,  3.64s/it]
Summarizing (BigBird-Pegasus):  76%|███████▌  | 76/100 [04:42<01:32,  3.84s/it]
Summarizing (BigBird-Pegasus):  77%|███████▋  | 77/100 [04:44<01:12,  3.17s/it]
Summarizing (BigBird-Pegasus):  78%|███████▊  | 78/100 [04:48<01:16,  3.48s/it]
Summarizing (BigBird-Pegasus):  79%|███████▉  | 79/100 [04:51<01:06,  3.19s/it]
Summarizing (BigBird-Pegasus):  80%|████████  | 80/100 [04:54<01:04,  3.25s/it]
Summarizing (BigBird-Pegasus):  81%|████████  | 81/100 [04:58<01:05,  3.43s/it]
Summarizing (BigBird-Pegasus):  82%|████████▏ | 82/100 [05:02<01:06,  3.68s/it]
Summarizing (BigBird-Pegasus):  83%|████████▎ | 83/100 [05:05<01:01,  3.62s/it]
Summarizing (BigBird-Pegasus):  84%|████████▍ | 84/100 [05:10<01:00,  3.79s/it]
Summarizing (BigBird-Pegasus):  85%|████████▌ | 85/100 [05:14<00:58,  3.93s/it]
Summarizing (BigBird-Pegasus):  86%|████████▌ | 86/100 [05:16<00:48,  3.48s/it]
Summarizing (BigBird-Pegasus):  87%|████████▋ | 87/100 [05:19<00:40,  3.11s/it]
Summarizing (BigBird-Pegasus):  88%|████████▊ | 88/100 [05:23<00:41,  3.43s/it]
Summarizing (BigBird-Pegasus):  89%|████████▉ | 89/100 [05:27<00:39,  3.59s/it]
Summarizing (BigBird-Pegasus):  90%|█████████ | 90/100 [05:31<00:38,  3.80s/it]
Summarizing (BigBird-Pegasus):  91%|█████████ | 91/100 [05:35<00:35,  3.92s/it]
Summarizing (BigBird-Pegasus):  92%|█████████▏| 92/100 [05:39<00:32,  4.02s/it]
Summarizing (BigBird-Pegasus):  93%|█████████▎| 93/100 [05:44<00:28,  4.08s/it]
Summarizing (BigBird-Pegasus):  94%|█████████▍| 94/100 [05:48<00:24,  4.11s/it]
Summarizing (BigBird-Pegasus):  95%|█████████▌| 95/100 [05:50<00:17,  3.48s/it]
Summarizing (BigBird-Pegasus):  96%|█████████▌| 96/100 [05:53<00:13,  3.36s/it]
Summarizing (BigBird-Pegasus):  97%|█████████▋| 97/100 [05:57<00:10,  3.65s/it]
Summarizing (BigBird-Pegasus):  98%|█████████▊| 98/100 [06:01<00:07,  3.61s/it]
Summarizing (BigBird-Pegasus):  99%|█████████▉| 99/100 [06:05<00:03,  3.80s/it]
Summarizing (BigBird-Pegasus): 100%|██████████| 100/100 [06:10<00:00,  3.70s/it]

             Model   ROUGE-1   ROUGE-2   ROUGE-L
0             BART  0.440294  0.200576  0.299882
1               T5  0.393009  0.166178  0.271495
2          Pegasus  0.413114  0.207893  0.301254
3          FLAN-T5  0.389524  0.160537  0.262596
4  BigBird-Pegasus  0.180260  0.024893  0.116558

In [19]:
from sklearn.metrics import precision_score

def calc_precision(reference, prediction):
    ref_tokens = set(reference.lower().split())
    pred_tokens = set(prediction.lower().split())
    tp = len(ref_tokens & pred_tokens)
    fp = len(pred_tokens - ref_tokens)
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    return precision

# Example for all models
precision_results = []

for m_info in model_infos:
    gen_col = f"{m_info['name']}_gen"
    precisions = [
        calc_precision(ref, pred)
        for ref, pred in zip(sample_df['highlights'], sample_df[gen_col])
    ]
    precision_results.append({
        "Model": m_info["name"],
        "Token Precision": np.mean(precisions)
    })

precision_df = pd.DataFrame(precision_results)
display(precision_df)

             Model  Token Precision
0             BART         0.379945
1               T5         0.387582
2          Pegasus         0.476856
3          FLAN-T5         0.338748
4  BigBird-Pegasus         0.177515

In [21]:
!pip install bert-score

from bert_score import score as bert_score

# For a single model:
P, R, F1 = bert_score(
    sample_df['BART_gen'].tolist(),    # preds
    sample_df['highlights'].tolist(),  # refs
    lang='en', rescale_with_baseline=True
)
print(f"BART BERTScore F1: {F1.mean():.4f}")

Collecting bert-score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: torch>=1.0.0 in c:\users\adidya\anaconda3\lib\site-packages (from bert-score) (2.6.0+cu126)
Requirement already satisfied: pandas>=1.0.1 in c:\users\adidya\anaconda3\lib\site-packages (from bert-score) (2.2.2)
Requirement already satisfied: transformers>=3.0.0 in c:\users\adidya\anaconda3\lib\site-packages (from bert-score) (4.52.4)
Requirement already satisfied: numpy in c:\users\adidya\anaconda3\lib\site-packages (from bert-score) (1.26.4)
Requirement already satisfied: requests in c:\users\adidya\anaconda3\lib\site-packages (from bert-score) (2.32.3)
Requirement already satisfied: tqdm>=4.31.1 in c:\users\adidya\anaconda3\lib\site-packages (from bert-score) (4.66.5)
Requirement already satisfied: matplotlib in c:\users\adidya\anaconda3\lib\site-packages (from bert-score) (3.9.2)
Requirement already satisfied: packaging>=20.9 in c:\users\adidya\anaconda3\lib\site-packages (from bert-score) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\adidya\anaconda3\lib\site-packages (from pandas>=1.0.1->bert-score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\adidya\anaconda3\lib\site-packages (from pandas>=1.0.1->bert-score) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\adidya\anaconda3\lib\site-packages (from pandas>=1.0.1->bert-score) (2023.3)
Requirement already satisfied: filelock in c:\users\adidya\anaconda3\lib\site-packages (from torch>=1.0.0->bert-score) (3.13.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\adidya\anaconda3\lib\site-packages (from torch>=1.0.0->bert-score) (4.11.0)
Requirement already satisfied: networkx in c:\users\adidya\anaconda3\lib\site-packages (from torch>=1.0.0->bert-score) (3.3)
Requirement already satisfied: jinja2 in c:\users\adidya\anaconda3\lib\site-packages (from torch>=1.0.0->bert-score) (3.1.4)
Requirement already satisfied: fsspec in c:\users\adidya\anaconda3\lib\site-packages (from torch>=1.0.0->bert-score) (2024.6.1)
Requirement already satisfied: setuptools in c:\users\adidya\anaconda3\lib\site-packages (from torch>=1.0.0->bert-score) (75.1.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\adidya\anaconda3\lib\site-packages (from torch>=1.0.0->bert-score) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\adidya\anaconda3\lib\site-packages (from sympy==1.13.1->torch>=1.0.0->bert-score) (1.3.0)
Requirement already satisfied: colorama in c:\users\adidya\anaconda3\lib\site-packages (from tqdm>=4.31.1->bert-score) (0.4.6)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in c:\users\adidya\anaconda3\lib\site-packages (from transformers>=3.0.0->bert-score) (0.31.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\adidya\anaconda3\lib\site-packages (from transformers>=3.0.0->bert-score) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in c:\users\adidya\anaconda3\lib\site-packages (from transformers>=3.0.0->bert-score) (2024.9.11)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\adidya\anaconda3\lib\site-packages (from transformers>=3.0.0->bert-score) (0.21.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\adidya\anaconda3\lib\site-packages (from transformers>=3.0.0->bert-score) (0.5.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\adidya\anaconda3\lib\site-packages (from matplotlib->bert-score) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\adidya\anaconda3\lib\site-packages (from matplotlib->bert-score) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\adidya\anaconda3\lib\site-packages (from matplotlib->bert-score) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\adidya\anaconda3\lib\site-packages (from matplotlib->bert-score) (1.4.4)
Requirement already satisfied: pillow>=8 in c:\users\adidya\anaconda3\lib\site-packages (from matplotlib->bert-score) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\adidya\anaconda3\lib\site-packages (from matplotlib->bert-score) (3.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\adidya\anaconda3\lib\site-packages (from requests->bert-score) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\adidya\anaconda3\lib\site-packages (from requests->bert-score) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\adidya\anaconda3\lib\site-packages (from requests->bert-score) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\adidya\anaconda3\lib\site-packages (from requests->bert-score) (2025.4.26)
Requirement already satisfied: six>=1.5 in c:\users\adidya\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert-score) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\adidya\anaconda3\lib\site-packages (from jinja2->torch>=1.0.0->bert-score) (2.1.3)
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
Installing collected packages: bert-score
Successfully installed bert-score-0.3.13

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

C:\Users\Adidya\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Adidya\M_H_Project\cache\models--roberta-large. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config.json:   0%|          | 0.00/482 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
WARNING:huggingface_hub.file_download:Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-large and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

BART BERTScore F1: 0.2822

FINE TUNED CODE: